# Generated by Django 4.2 on 2023-04-24 13:19

import cloudinary.models
from django.db import migrations, models
import guide_project.storages_backends
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(default=1)),
                ('serial_no', models.IntegerField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('domain_1', models.CharField(max_length=200)),
                ('domain_2', models.CharField(blank=True, max_length=200)),
                ('domain_3', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('myImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('vacancy', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Otp_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('temp_email', models.CharField(blank=True, max_length=100, null=True)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=500)),
                ('project_domain', models.CharField(max_length=100, null=True)),
                ('project_description', models.TextField(null=True)),
                ('no_of_members', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('reg_no_1', models.BigIntegerField()),
                ('student_1_name', models.CharField(max_length=100)),
                ('student_1_email', models.CharField(max_length=100)),
                ('student_1_no', models.BigIntegerField()),
                ('reg_no_2', models.BigIntegerField(blank=True, null=True)),
                ('student_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_email', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_no', models.BigIntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.user_directory_path)),
                ('ppt', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.user_directory_path)),
                ('rs_paper', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.user_directory_path)),
                ('guide_form', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.user_directory_path)),
                ('app_video', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.app_instance_path)),
                ('product_video', models.FileField(blank=True, null=True, storage=guide_project.storages_backends.MediaStorage(), upload_to=pages.models.product_instance_path)),
                ('profile_approved', models.BooleanField(default=False)),
                ('guide_approved', models.BooleanField(default=False)),
                ('rs_paper_approved', models.BooleanField(default=False)),
                ('docs_approved', models.BooleanField(default=False)),
                ('ppt_approved', models.BooleanField(default=False)),
                ('guide', models.CharField(max_length=100)),
                ('guide_email', models.CharField(max_length=100)),
                ('review_2_marks', models.IntegerField()),
                ('review_3_marks', models.IntegerField()),
                ('communicated', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Project Type', 'Project Type'), ('Applicatio Based', 'Application Based'), ('Product Based', 'Product Based')], default=('Project Type', 'Project Type'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamID', models.CharField(default='CSE', max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_domain', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('no_of_members', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10)),
                ('reg_no_1', models.BigIntegerField()),
                ('student_1_name', models.CharField(max_length=100)),
                ('student_1_email', models.CharField(max_length=100)),
                ('student_1_no', models.BigIntegerField()),
                ('reg_no_2', models.BigIntegerField(blank=True, null=True)),
                ('student_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_email', models.CharField(blank=True, max_length=100, null=True)),
                ('student_2_no', models.BigIntegerField(blank=True, null=True)),
                ('guide_email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temp_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
