# Generated by Django 4.2 on 2023-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='team',
            name='app_video',
        ),
        migrations.RemoveField(
            model_name='team',
            name='communicated',
        ),
        migrations.RemoveField(
            model_name='team',
            name='payment_done',
        ),
        migrations.RemoveField(
            model_name='team',
            name='product_video',
        ),
        migrations.RemoveField(
            model_name='team',
            name='review_2_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='review_3_marks',
        ),
        migrations.RemoveField(
            model_name='team',
            name='type',
        ),
    ]
