# Generated by Django 4.2 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_team_accepted_remove_team_app_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='communicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
