# Generated by Django 4.2 on 2023-04-24 13:33

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_team_accepted_team_communicated_team_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='app_video',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.app_instance_path),
        ),
        migrations.AddField(
            model_name='team',
            name='product_video',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.product_instance_path),
        ),
        migrations.AddField(
            model_name='team',
            name='review_2_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='review_3_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Project Type', 'Project Type'), ('Applicatio Based', 'Application Based'), ('Product Based', 'Product Based')], default=('Project Type', 'Project Type'), max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='guide_form',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='ppt',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='rs_paper',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
    ]
