# Generated by Django 4.2 on 2023-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_team_app_video_team_product_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='review_2_marks',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='review_3_marks',
            field=models.IntegerField(default=-1),
        ),
    ]
