# Generated by Django 4.2 on 2023-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_team_review_3_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='domain_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='domain_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
