# Generated by Django 4.0.4 on 2023-02-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_team_document_alter_team_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=models.ImageField(upload_to='', verbose_name='images'),
        ),
    ]
