# Generated by Django 4.0.4 on 2023-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=models.ImageField(upload_to='guide-images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
