# Generated by Django 4.0.4 on 2023-02-18 07:44

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_alter_team_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
    ]
