# Generated by Django 4.0.4 on 2023-02-18 10:23

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='document',
            field=models.FileField(upload_to=pages.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='reg_no_1',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_1_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_1_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_1_no',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='temp_team',
            name='project_description',
            field=models.TextField(),
        ),
    ]
