# Generated by Django 4.0.4 on 2023-02-26 08:32

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_alter_guide_designation_alter_team_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ppt',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='team',
            name='rs_paper',
            field=models.FileField(blank=True, null=True, upload_to=pages.models.user_directory_path),
        ),
    ]
