# Generated by Django 4.0.4 on 2023-03-13 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_team_ppt_team_rs_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
