# Generated by Django 4.0.4 on 2023-03-15 06:54

from django.db import migrations, models
import pages.custom_storage
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_alter_team_rs_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='document',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.DocStorage, upload_to=pages.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='ppt',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.DocStorage, upload_to=pages.models.user_directory_path),
        ),
    ]
