# Generated by Django 4.0.4 on 2023-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_alter_team_document_alter_team_ppt'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='docs_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='guide_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='profile_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='rs_paper_approved',
            field=models.BooleanField(default=False),
        ),
    ]
