# Generated by Django 4.0.4 on 2023-03-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_team_docs_approved_team_guide_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='is_approved',
            new_name='ppt_approved',
        ),
    ]
