# Generated by Django 4.0.4 on 2023-03-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0054_rename_is_approved_team_ppt_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='project_domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamID',
            field=models.CharField(max_length=500),
        ),
    ]
