# Generated by Django 4.0.4 on 2023-03-23 15:29

from django.db import migrations, models
import pages.custom_storage
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_alter_team_project_name_alter_team_teamid'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='guide_form',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.DocStorage, upload_to=pages.models.user_directory_path),
        ),
    ]
