# Generated by Django 4.0.4 on 2023-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_team_guide_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='review_1_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='review_2_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
