# Generated by Django 4.0.4 on 2023-04-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_team_review_1_marks_team_review_2_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='review_1_marks',
            new_name='review_3_marks',
        ),
    ]
