# Generated by Django 4.0.4 on 2023-04-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_rename_review_1_marks_team_review_3_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='communicated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
