# Generated by Django 4.0.4 on 2023-04-13 14:42

import cloudinary.models
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0060_team_accepted_team_communicated_team_payment_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('img', cloudinary.models.CloudinaryField(max_length=255, verbose_name=pages.models.credit_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name=pages.models.guide_directory_path),
        ),
    ]
