# Generated by Django 4.0.4 on 2023-04-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0062_alter_credit_img_alter_guide_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(blank=True, choices=[('App Based', 'App Based'), ('Product Based', 'Product Based')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='no_of_members',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='temp_team',
            name='no_of_members',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
