# Generated by Django 4.0.4 on 2023-04-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0063_team_type_alter_team_no_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('App Based', 'App Based'), ('Product Based', 'Product Based')], default=('App Based', 'App Based'), max_length=200),
        ),
    ]
