# Generated by Django 4.0.4 on 2023-04-22 07:11

from django.db import migrations, models
import pages.custom_storage
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_alter_team_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='app_video',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.DocStorage, upload_to=pages.models.app_instance_path),
        ),
        migrations.AddField(
            model_name='team',
            name='product_video',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.DocStorage, upload_to=pages.models.product_instance_path),
        ),
    ]
