# Generated by Django 4.0.4 on 2023-04-22 17:44

from django.db import migrations, models
import pages.custom_storage
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_team_app_video_team_product_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='app_video',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.MediaStorage, upload_to=pages.models.app_instance_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='product_video',
            field=models.FileField(blank=True, null=True, storage=pages.custom_storage.MediaStorage, upload_to=pages.models.product_instance_path),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Project Type', 'Project Type'), ('Applicatio Based', 'Application Based'), ('Product Based', 'Product Based')], default=('Project Type', 'Project Type'), max_length=200),
        ),
    ]
