# Generated by Django 4.0.4 on 2023-03-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_comment_published_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
